version: '3'

networks:
  backend:
    driver: bridge


services:
  ### php-apache-server ################################################
  app:
    build:
      context: ./php-apache
    volumes:
      - ./php-apache/php.ini:/usr/local/etc/php/php.ini
      - ../:/var/www/html
    ports:
      - "80:80"
    networks:
      - backend

  ## MySQL ################################################
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=xspeed_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pw_xspeed_db
      - MYSQL_ROOT_PASSWORD=pw_xspeed_db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend

  ## PhpmyAdmin ################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pw_xspeed_db
      - MYSQL_ROOT_PASSWORD=pw_xspeed_db
    ports:
      - "8080:80"
    networks:
      - backend